---
/**:
  ros__parameters:

    general:
      camera_model: 'zed2i'
      camera_name: 'zed2i'       # bisa diubah via launch arg
      grab_resolution: 'HD1080'   # 'HD2K', 'HD1080', 'HD720', 'VGA', 'AUTO'
      grab_frame_rate: 30        # ZED SDK grabbing rate (FPS)
      pub_frame_rate: 30.0
      gpu_id: 0               # -1 = auto, atau 0 untuk Orin Nano

    video:
      brightness: 4              # [DYNAMIC] 0–8
      contrast: 4                # [DYNAMIC] 0–8
      hue: 0                     # [DYNAMIC] 0–11
      saturation: 4              # [DYNAMIC] 0–8
      sharpness: 4               # [DYNAMIC] 0–8
      gamma: 8                   # [DYNAMIC] 1–9
      auto_exposure_gain: true   # auto exposure & gain
      gain: 50                   # manual gain (0–100) kalau auto_exposure_gain=false
      exposure: 50               # manual exposure (0–100) kalau auto_exposure_gain=false
      auto_whitebalance: true
      whitebalance_temperature: 42 # jika auto_whitebalance=false
      compressed_stream: true    # aktifkan compressed image stream

    depth:
        depth_mode: 'ULTRA'        # 'NONE','PERFORMANCE','QUALITY','ULTRA'
        min_depth: 0.3
        max_depth: 15.0
        depth_stabilization: 2
        openni_depth_mode: false
        confidence_threshold: 40          # opsional (lebih toleran)
        textureness_confidence_threshold: 40

    pos_tracking:
      pos_tracking_enabled: true # ⬅️ harus true untuk elevation/Nvblox
      publish_tf: false          # publish odom->base_link->camera_link TF
      publish_map_tf: false      # map->odom TF (set true kalau butuh global map)
      area_memory: false
      area_memory_db_path: ""
      imu_fusion: true           # gunakan IMU untuk VIO fusion

    sensors:
      sensors_timestamp_sync: true
      publish_imu_tf: false      # publish TF untuk IMU link (opsional)
      publish_imu: true          # publish sensor_msgs/Imu
      publish_magnetometer: false
      publish_temperature: false
      publish_pressure: false

    mapping:
      enabled: true             # biarkan false kalau pakai nvblox/elevation_mapping

    diagnostics:
      pub_period: 1.0            # diagnostic msg period (s)
